services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: api
    ports:
      - "5000:5000"
  web-app:
    build:
      context: .
      dockerfile: web_app/Dockerfile
    container_name: web-app
    ports:
      - "5001:5001"
    depends_on:
      - api
