stages:
  prepare:
    cmd: python3 src/data/prepare_dataset.py
    deps:
    - data/raw/fashion_mnist
    - src/data/prepare_dataset.py
    params:
    - prepare.supervision
    - prepare.random_state
    outs:
    - data/processed/x.npy
    - data/processed/x_test.npy
    - data/processed/y_test.npy
    - data/processed/y_train.npy
    - data/ge/fashion_mnist.csv
  train:
    cmd: PYTHONHASHSEED=0 python3 src/models/train_model.py
    deps:
    - data/processed/x.npy
    - data/processed/y_train.npy
    - src/models/train_model.py
    params:
    - train.batch_size
    - train.epochs
    - train.max_iter
    - train.tol
    - train.random_state
    outs:
    - models/model.tf
  evaluate:
    cmd: python3 src/models/evaluate_model.py
    deps:
    - data/processed/x_test.npy
    - data/processed/y_test.npy
    - models/model.tf
    - src/models/evaluate_model.py
    outs:
    - models/score.json
