{
 "title": "Grafana Dashboard",
 "description": "Dashboard for SDCEC API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total number of requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_model_http_requests_total{handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Type of requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (api_model_http_requests_total{handler!=\"/metrics\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_model_http_requests_total{handler!=\"/metrics\", status!=\"2xx\"})"
    }
   ]
  },
  {
   "title": "Request rate in the last minute",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_model_http_requests_total{handler!=\"/metrics\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(api_model_http_requests_total{handler!=\"/metrics\"}[$__interval]))",
     "legendFormat": "HTTP requests"
    }
   ]
  },
  {
   "title": "Endpoint requests in the last 30s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(api_model_http_requests_total{handler!=\"/metrics\"}[$__interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Predicted classes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_model_class_prediction_total",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Average prediction time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_model_http_request_duration_seconds_sum{handler=\"/model\", method=\"POST\", status=\"2xx\"} / api_model_http_request_duration_seconds_count{handler=\"/model\", method=\"POST\", status=\"2xx\"}"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_model_http_request_size_bytes_sum{method=\"POST\", status=\"2xx\"}"
    }
   ]
  }
 ]
}