name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install DVC
        run: |
          pip install -U pip
          pip install dvc
      - name: Download model
        run: dvc pull models/model.tf models/score.json
      - name: Install Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
      - name: Use Okteto Cloud
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
      - name: Build
        run: okteto build
      - name: Deploy
        run: okteto deploy
