name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
      - name: Use Okteto Cloud
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
      - name: Build and deploy
        run: okteto deploy --build
